/*
* generated by Xtext
*/
package com.ironglass.hdlforge;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SystemVerilogUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.ironglass.hdlforge.ui.internal.SystemVerilogActivator.getInstance().getInjector("com.ironglass.hdlforge.SystemVerilog");
	}
	
}
