/*
* generated by Xtext
*/
package com.ironglass.hdlforge.ui.contentassist;

import com.ironglass.hdlforge.ui.contentassist.AbstractSystemVerilogProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SystemVerilogProposalProvider extends AbstractSystemVerilogProposalProvider {

}
