/*
 * generated by Xtext
 */
package com.ironglass.hdlforge.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SystemVerilogExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.ironglass.hdlforge.ui.internal.SystemVerilogActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.ironglass.hdlforge.ui.internal.SystemVerilogActivator.getInstance().getInjector("com.ironglass.hdlforge.SystemVerilog");
	}
	
}
