/*
* generated by Xtext
*/
package com.ironglass.hdlforge.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SystemVerilogOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
