/*
 * generated by Xtext
 */
package com.ironglass.hdlforge;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SystemVerilogRuntimeModule extends com.ironglass.hdlforge.AbstractSystemVerilogRuntimeModule {

}
