/*
 * generated by Xtext
 */
package com.ironglass.hdlforge.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SystemVerilogUiModule extends com.ironglass.hdlforge.ui.AbstractSystemVerilogUiModule {
	public SystemVerilogUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
