<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemVerilog"
    nsURI="http://www.ironglass.com/hdlforge/SystemVerilog" nsPrefix="systemVerilog">
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass platform:/resource/com.ironglass.hdlforge/src-gen/com/ironglass/hdlforge/SystemVerilog.ecore#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="ecore:EClass platform:/resource/com.ironglass.hdlforge/src-gen/com/ironglass/hdlforge/SystemVerilog.ecore#//Port"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module_items" upperBound="-1"
        eType="ecore:EClass platform:/resource/com.ironglass.hdlforge/src-gen/com/ironglass/hdlforge/SystemVerilog.ecore#//Module_item"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module_item"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VARIABLE_DECLARATION" eSuperTypes="platform:/resource/com.ironglass.hdlforge/src-gen/com/ironglass/hdlforge/SystemVerilog.ecore#//Module_item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
