/*
* generated by Xtext
*/
package com.ironglass.hdlforge.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.ironglass.hdlforge.services.SystemVerilogGrammarAccess;

public class SystemVerilogParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SystemVerilogGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.ironglass.hdlforge.parser.antlr.internal.InternalSystemVerilogParser createParser(XtextTokenStream stream) {
		return new com.ironglass.hdlforge.parser.antlr.internal.InternalSystemVerilogParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public SystemVerilogGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SystemVerilogGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
